
language: node_js
node_js:
  - '12'
install:
  - yarn
script:
  - npm build
  - cp index.d.ts dist/
# after_script:
  # - npminstall codecov && codecov

deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_token: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
